# Generated by Django 5.2.13 on 2026-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_name_9ff0a3_idx',
            old_name='products_pr_name_8e1b52_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_sku_ca0cdc_idx',
            old_name='products_pr_sku_496f25_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_is_acti_952083_idx',
            old_name='products_pr_is_acti_d9e966_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, upload_to='products/'),
        ),
    ]
